export const ADD_CART='ADD_CART';
export const CHANGE_MESSAGE='CHANGE_MESSAGE';
export const DELETE_CARTS='DELETE_CARTS';
export const PLUS_CART_ITEM='PLUS_CART_ITEM';
export const MINUS_CART_ITEM='MINUS_CART_ITEM';